targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-b5kqx-56588d7df7xxcb68-jl6st: 20
  ecoqube-dev-default-worker-topo-b5kqx-56588d7df7xxcb68-lq2xn: 30
  ecoqube-dev-default-worker-topo-b5kqx-56588d7df7xxcb68-v6vqr: 50