targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-zchvw-7bd9654cffx4l5sb-hltzm: 20
  ecoqube-dev-default-worker-topo-zchvw-7bd9654cffx4l5sb-cmsh5: 30
  ecoqube-dev-default-worker-topo-zchvw-7bd9654cffx4l5sb-nzbcb: 50