targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-6b29x-55c6766555-7w28s: 20
  ecoqube-dev-default-worker-topo-6b29x-55c6766555-jp4t4: 30
  ecoqube-dev-default-worker-topo-6b29x-55c6766555-x2l9n: 50
