targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-dt48g-b99d74ddc-mxj5x: 20
  ecoqube-dev-default-worker-topo-dt48g-b99d74ddc-nd6dg: 30
  ecoqube-dev-default-worker-topo-dt48g-b99d74ddc-vhjkd: 50
