targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-plnt7-5cbc848c9b-8rw2p: 20
  ecoqube-dev-default-worker-topo-plnt7-5cbc848c9b-dbt9p: 30
  ecoqube-dev-default-worker-topo-plnt7-5cbc848c9b-r52sw: 50