targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-x9xvk-84f6bd7f56-7v7rd: 20
  ecoqube-dev-default-worker-topo-x9xvk-84f6bd7f56-ht2x5: 30
  ecoqube-dev-default-worker-topo-x9xvk-84f6bd7f56-scqbv: 50