targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-7lwmb-6d8dfffbb5-4rwtt: 20
  ecoqube-dev-default-worker-topo-7lwmb-6d8dfffbb5-9p528: 30
  ecoqube-dev-default-worker-topo-7lwmb-6d8dfffbb5-nlzmq: 50
