targetMetricName: "fake_energy_target"
targets:
  ecoqube-dev-default-worker-topo-vwhzd-97cf45665-m6mqz: 20
  ecoqube-dev-default-worker-topo-vwhzd-97cf45665-psmc7: 30
  ecoqube-dev-default-worker-topo-vwhzd-97cf45665-wtksh: 50
