apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  labels:
    {{- include "target-exporter.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "ecoqube-dev.kubeconfig").AsSecrets | trimSuffix "\n" | indent 2 -}}