apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "target-exporter.fullname" . }}
  labels:
    {{- include "target-exporter.labels" . | nindent 4 }}
    {{- toYaml .Values.scrapeLabel | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "target-exporter.name" . }}
  endpoints:
    - port: {{ .Values.service.name }}