apiVersion: v1
kind: Service
metadata:
  name: {{ include "target-exporter.fullname" . }}
  labels:
    {{- include "target-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: backend
  selector:
    {{- include "target-exporter.selectorLabels" . | nindent 4 }}
