apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-exporter
  namespace: target-exporter
spec:
  replicas: 1
  template:
    metadata:
      name: target-exporter
      labels:
        app: target-exporter
    spec:
      containers:
        - name: target-exporter
          image: docker.io/hazxel/target-exporter:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 2112
      restartPolicy: Always
  selector:
    matchLabels:
      app: target-exporter
