apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: default
  serviceMonitorSelector:
    matchLabels:
      release: target-exporter
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false