apiVersion: v1
kind: Service
metadata:
  name: target-exporter
  labels:
    app: target-exporter
    release: kube-prometheus-stack
spec:
  selector:
    app: target-exporter
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
      protocol: TCP
  type: NodePort