apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: target-exporter
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - target-exporter
  selector:
    matchLabels:
      app: target-exporter
  endpoints:
    - port: metrics